"package: app_close":
  - "double-back-to-close"
"package: package_info":
  - "package-info"
"package: no_screenshot":
  - "no-screenshot"
"package: firebase_crashlytics":
  - "firebase-crashlytics"
"package: nativephp_datetime_picker":
  - "nativephp-datetime-picker"
"package: nativephp_social_auth":
  - "nativephp-social-auth"